import { createOpenAI } from "@ai-sdk/openai";
import { streamText } from "ai";
import { Hono } from "hono";

// Global Env is auto-generated by `pnpm cf-typegen` from wrangler.toml [vars]
const app = new Hono<{ Bindings: Env }>();

// ── Assistant-UI wire format types ───────────────────────────────────────────

type MessagePart =
	| { type: "text"; text: string }
	| { type: "image"; image?: string; url?: string }
	| { type: "image_url"; image_url?: { url: string }; url?: string }
	| { type: "file"; mediaType?: string; url?: string; name?: string };

type UIMessage = {
	role: string;
	parts?: MessagePart[];
	content?: string;
};

// ── OpenRouter format builders ───────────────────────────────────────────────
// Reference: https://openrouter.ai/docs/guides/overview/multimodal/overview

type OpenRouterContentPart =
	| { type: "text"; text: string }
	| { type: "image_url"; image_url: { url: string } }
	| { type: "file"; file: { filename: string; file_data: string } }
	| { type: "input_audio"; input_audio: { data: string; format: string } }
	| { type: "video_url"; video_url: { url: string } };

/** Extract raw base64 from a data URL (strips the data:mime;base64, header). */
function extractBase64(dataUrl: string): string {
	const idx = dataUrl.indexOf(",");
	return idx >= 0 ? dataUrl.slice(idx + 1) : dataUrl;
}

/** Convert a single Assistant-UI MessagePart to OpenRouter's wire format. */
function toOpenRouterPart(p: MessagePart): OpenRouterContentPart | null {
	if (p.type === "text") return { type: "text", text: p.text };

	// image / image_url → image_url format (OpenRouter standard)
	if (p.type === "image" || p.type === "image_url") {
		const url =
			p.type === "image_url"
				? (p.image_url?.url ?? p.url ?? "")
				: (p.image ?? p.url ?? "");
		return { type: "image_url", image_url: { url } };
	}

	// file → dispatch by MIME type
	if (p.type === "file") {
		const url = p.url ?? "";
		const mime = p.mediaType ?? "application/octet-stream";
		const filename = p.name ?? `attachment.${mime.split("/")[1] ?? "bin"}`;

		if (mime.startsWith("image/")) {
			return { type: "image_url", image_url: { url } };
		}
		if (mime === "application/pdf") {
			return { type: "file", file: { filename, file_data: url } };
		}
		if (mime.startsWith("audio/")) {
			const format = mime.split("/")[1] ?? "wav";
			return {
				type: "input_audio",
				input_audio: { data: extractBase64(url), format },
			};
		}
		if (mime.startsWith("video/")) {
			return { type: "video_url", video_url: { url } };
		}
	}

	return null;
}

/** Build complete OpenRouter messages array including system prompt. */
function buildOpenRouterMessages(
	uiMessages: UIMessage[],
	systemPrompt: string,
): Array<{ role: string; content: string | OpenRouterContentPart[] }> {
	const result: Array<{
		role: string;
		content: string | OpenRouterContentPart[];
	}> = [{ role: "system", content: systemPrompt }];

	for (const m of uiMessages) {
		if (m.parts?.length) {
			const parts = m.parts
				.map(toOpenRouterPart)
				.filter((p): p is OpenRouterContentPart => p !== null);
			result.push({ role: m.role, content: parts });
		} else {
			result.push({ role: m.role, content: m.content ?? "" });
		}
	}

	return result;
}

// ── Routes ────────────────────────────────────────────────────────────────────

app.get("/api/health", (c) => c.json({ status: "ok", name: "roast-prof" }));

app.post("/api/chat", async (c) => {
	try {
		const { messages } = await c.req.json<{ messages: UIMessage[] }>();

		if (!c.env.API_KEY) return c.json({ error: "Missing API_KEY secret" }, 500);
		if (!c.env.MODEL) return c.json({ error: "Missing MODEL env var" }, 500);

		const systemPrompt =
			"你现在是林亦频道的「暴躁教授」。用极其刻薄、但也足够专业的学术口吻回答问题。偶尔嘲讽用户的无知，偶尔冷幽默。保持中文，短句为主。";

		// Build raw OpenRouter message format upfront
		const openRouterMessages = buildOpenRouterMessages(messages, systemPrompt);

		const model = c.env.MODEL;
		console.log(
			`[Worker] ${messages.length} msgs → ${model} (multimodal: ${messages.some((m) => m.parts?.some((p) => p.type !== "text"))})`,
		);

		const provider = createOpenAI({
			baseURL: c.env.BASE_URL,
			apiKey: c.env.API_KEY,
			// Simulate request origin for OpenRouter routing & analytics
			headers: {
				"HTTP-Referer": c.env.SITE_URL,
				"X-OpenRouter-Title": c.env.SITE_NAME,
				"X-OpenRouter-Categories": c.env.SITE_CATEGORIES,
			},
			// Intercept the request to inject the correctly-formatted OpenRouter messages.
			// The SDK validates its own types, but the actual wire payload uses OpenRouter's format.
			fetch: async (url, options) => {
				const body = JSON.parse((options as RequestInit).body as string);
				body.messages = openRouterMessages;
				return fetch(url as string, {
					...(options as RequestInit),
					body: JSON.stringify(body),
				});
			},
		});

		// streamText handles streaming/response format; actual request is intercepted above
		const result = streamText({
			model: provider.chat(model),
			messages: [{ role: "user", content: "." }], // placeholder — real messages injected via fetch
		});

		return result.toUIMessageStreamResponse();
	} catch (error: unknown) {
		const msg = error instanceof Error ? error.message : "Unknown error";
		console.error("[Worker] /api/chat error:", msg);
		return c.json({ error: msg }, 500);
	}
});

export default app;
