import { createOpenAI } from "@ai-sdk/openai";
import { streamText } from "ai";
import { Hono } from "hono";

// Global Env is auto-generated by `pnpm cf-typegen` from wrangler.toml [vars]
const app = new Hono<{ Bindings: Env }>();

// ── Assistant-UI wire format types ───────────────────────────────────────────

type MessagePart =
	| { type: "text"; text: string }
	| { type: "image"; image?: string; url?: string }
	| { type: "image_url"; image_url?: { url: string }; url?: string }
	| { type: "file"; mediaType?: string; url?: string; name?: string };

type UIMessage = {
	role: string;
	parts?: MessagePart[];
	content?: string;
};

// ── OpenRouter format builders ───────────────────────────────────────────────
// Reference: https://openrouter.ai/docs/guides/overview/multimodal/overview

type OpenRouterContentPart =
	| { type: "text"; text: string }
	| { type: "image_url"; image_url: { url: string } }
	| { type: "file"; file: { filename: string; file_data: string } }
	| { type: "input_audio"; input_audio: { data: string; format: string } }
	| { type: "video_url"; video_url: { url: string } };

/** Extract raw base64 from a data URL (strips the data:mime;base64, header). */
function extractBase64(dataUrl: string): string {
	const idx = dataUrl.indexOf(",");
	return idx >= 0 ? dataUrl.slice(idx + 1) : dataUrl;
}

/** Convert a single AssistantUI MessagePart → OpenRouter wire format. */
function toOpenRouterPart(p: MessagePart): OpenRouterContentPart | null {
	if (p.type === "text") return { type: "text", text: p.text };

	if (p.type === "image" || p.type === "image_url") {
		const url =
			p.type === "image_url"
				? (p.image_url?.url ?? p.url ?? "")
				: (p.image ?? p.url ?? "");
		return { type: "image_url", image_url: { url } };
	}

	if (p.type === "file") {
		const url = p.url ?? "";
		const mime = p.mediaType ?? "application/octet-stream";
		const filename = p.name ?? `attachment.${mime.split("/")[1] ?? "bin"}`;

		if (mime.startsWith("image/"))
			return { type: "image_url", image_url: { url } };
		if (mime === "application/pdf")
			return { type: "file", file: { filename, file_data: url } };
		if (mime.startsWith("audio/"))
			return {
				type: "input_audio",
				input_audio: {
					data: extractBase64(url),
					format: mime.split("/")[1] ?? "wav",
				},
			};
		if (mime.startsWith("video/"))
			return { type: "video_url", video_url: { url } };
	}

	return null;
}

/** Build complete OpenRouter messages array (system + conversation). */
function buildOpenRouterMessages(
	uiMessages: UIMessage[],
	systemPrompt: string,
): Array<{ role: string; content: string | OpenRouterContentPart[] }> {
	const result: Array<{
		role: string;
		content: string | OpenRouterContentPart[];
	}> = [{ role: "system", content: systemPrompt }];

	for (const m of uiMessages) {
		if (m.parts?.length) {
			const parts = m.parts
				.map(toOpenRouterPart)
				.filter((p): p is OpenRouterContentPart => p !== null);
			result.push({ role: m.role, content: parts });
		} else {
			result.push({ role: m.role, content: m.content ?? "" });
		}
	}
	return result;
}

// ── SSE streaming transform ───────────────────────────────────────────────────
// OpenRouter returns `delta.reasoning` for reasoning models.
// @ai-sdk/openai recognises `delta.reasoning_content` (OpenAI o-series naming).
// We line-buffer the SSE stream and rename the field so the SDK surfaces it as
// ReasoningPart in toUIMessageStreamResponse(), which the frontend renders.

function transformReasoningSSE(response: Response): Response {
	if (!response.body) return response;

	const encoder = new TextEncoder();
	const decoder = new TextDecoder();
	let buffer = "";

	const transform = new TransformStream<Uint8Array, Uint8Array>({
		transform(chunk, controller) {
			buffer += decoder.decode(chunk, { stream: true });
			const lines = buffer.split("\n");
			buffer = lines.pop() ?? "";

			for (const line of lines) {
				if (!line.startsWith("data: ")) {
					controller.enqueue(encoder.encode(`${line}\n`));
					continue;
				}
				const data = line.slice(6).trim();
				if (data === "[DONE]") {
					controller.enqueue(encoder.encode(`${line}\n`));
					continue;
				}
				try {
					const json = JSON.parse(data);
					if (Array.isArray(json.choices)) {
						for (const choice of json.choices) {
							if (
								choice.delta &&
								choice.delta.reasoning !== undefined &&
								choice.delta.reasoning_content === undefined
							) {
								choice.delta.reasoning_content = choice.delta.reasoning;
								delete choice.delta.reasoning;
							}
						}
					}
					controller.enqueue(encoder.encode(`data: ${JSON.stringify(json)}\n`));
				} catch {
					controller.enqueue(encoder.encode(`${line}\n`));
				}
			}
		},
		flush(controller) {
			if (buffer) controller.enqueue(encoder.encode(buffer));
		},
	});

	return new Response(response.body.pipeThrough(transform), {
		status: response.status,
		statusText: response.statusText,
		headers: response.headers,
	});
}

// ── Routes ────────────────────────────────────────────────────────────────────

app.get("/api/health", (c) => c.json({ status: "ok", name: "roast-prof" }));

app.post("/api/chat", async (c) => {
	try {
		const { messages } = await c.req.json<{ messages: UIMessage[] }>();

		if (!c.env.API_KEY) return c.json({ error: "Missing API_KEY secret" }, 500);
		if (!c.env.MODEL) return c.json({ error: "Missing MODEL env var" }, 500);

		const systemPrompt =
			"你现在是林亦频道的「暴躁教授」。用极其刻薄、但也足够专业的学术口吻回答问题。偶尔嘲讽用户的无知，偶尔冷幽默。保持中文，短句为主。";

		const openRouterMessages = buildOpenRouterMessages(messages, systemPrompt);
		const model = c.env.MODEL;

		const isMultimodal = messages.some((m) =>
			m.parts?.some((p) => p.type !== "text"),
		);
		console.log(
			`[Worker] ${messages.length} msgs → ${model} (multimodal: ${isMultimodal})`,
		);

		const provider = createOpenAI({
			baseURL: c.env.BASE_URL,
			apiKey: c.env.API_KEY,
			headers: {
				"HTTP-Referer": c.env.SITE_URL,
				"X-OpenRouter-Title": c.env.SITE_NAME,
				"X-OpenRouter-Categories": c.env.SITE_CATEGORIES,
			},
			fetch: async (url, options) => {
				// Inject OpenRouter-formatted messages
				const body = JSON.parse((options as RequestInit).body as string);
				body.messages = openRouterMessages;
				const raw = await fetch(url as string, {
					...(options as RequestInit),
					body: JSON.stringify(body),
				});
				// Map delta.reasoning → delta.reasoning_content for SDK recognition
				return transformReasoningSSE(raw);
			},
		});

		const result = streamText({
			model: provider.chat(model),
			messages: [{ role: "user", content: "." }], // placeholder — real messages injected via fetch
		});

		return result.toUIMessageStreamResponse();
	} catch (error: unknown) {
		const msg = error instanceof Error ? error.message : "Unknown error";
		console.error("[Worker] /api/chat error:", msg);
		return c.json({ error: msg }, 500);
	}
});

export default app;
